name: Integration tests
on:
  push:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:
jobs:
  integration:
    name: Integration tests
    runs-on: ubuntu-24.04
    env:
      MSHOULD_FAST: 1
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4
        with:
          submodules: true
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: 22
      - run: node integration.js
      - uses: actions/upload-artifact@v4
        with:
          name: integration-logs
          path: work/logs
          overwrite: true
          # compression-level: 9
