name: Run integration tests
on:
  push:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:
jobs:
  integration:
    name: Integration tests
    runs-on: ubuntu-24.04
    env:
      MSHOULD_FAST: 1
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          registry-url: "https://registry.npmjs.org"
          cache: npm
          node-version: 22
      - run: node integration.js
      - uses: actions/upload-artifact@v4
        with:
          name: integration-logs
          path: work/logs
          overwrite: true
          # compression-level: 9
  fuzz:
    name: Fuzzing
    runs-on: ubuntu-22.04
    env:
      MSHOULD_FAST: 1
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4
        with:
          submodules: true
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          registry-url: "https://registry.npmjs.org"
          cache: npm
          node-version: 22
      - run: git clone https://github.com/paulmillr/noble-curves curves
      - run: cd curves; npm install; npm run build
      - run: sudo apt install -qy bzip2 build-essential libc++-dev libc++abi-dev lsb-release software-properties-common gnupg libboost-all-dev xxd cmake git wget curl bc jq
        name: Install apt dependencies
      - run: wget https://apt.llvm.org/llvm.sh; chmod +x llvm.sh; sudo ./llvm.sh 15
        name: Install LLVM 15
      - run: sudo ln -s /usr/lib/llvm-14/include/c++/v1 /usr/include/c++/v1
      - run: ls -lah /usr/include/c++
      - run: cd curves; npm install; npm run test
      - run: cd cryptofuzz/modules/noble-curves; make clean
      - run: cd cryptofuzz; bash ./build.sh
      - run: cd cryptofuzz; bash ./build.sh fast
      - run: cd cryptofuzz; ./cryptofuzz -verbosity=1 -create_missing_dirs=1 -runs=100000
