name: Run integration tests
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
jobs:
  node:
    name: Node v22
    runs-on: ubuntu-24.04-arm
    env:
      MSHOULD_FAST: 1
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          registry-url: "https://registry.npmjs.org"
          cache: npm
          node-version: 22
      - run: node integr.js
